//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcgnuX.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcgnuX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 账号 的本地化字符串。
        /// </summary>
        public static string S_Account {
            get {
                return ResourceManager.GetString("S_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string S_Add {
            get {
                return ResourceManager.GetString("S_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动下载 的本地化字符串。
        /// </summary>
        public static string S_AutoDownload {
            get {
                return ResourceManager.GetString("S_AutoDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 容我再想想 的本地化字符串。
        /// </summary>
        public static string S_Cancel {
            get {
                return ResourceManager.GetString("S_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string S_Confirm {
            get {
                return ResourceManager.GetString("S_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制账号 的本地化字符串。
        /// </summary>
        public static string S_CopyAccount {
            get {
                return ResourceManager.GetString("S_CopyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制密码 的本地化字符串。
        /// </summary>
        public static string S_CopyPassword {
            get {
                return ResourceManager.GetString("S_CopyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抓取地址 的本地化字符串。
        /// </summary>
        public static string S_CrawlAddress {
            get {
                return ResourceManager.GetString("S_CrawlAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抓取页数 的本地化字符串。
        /// </summary>
        public static string S_CrawlPages {
            get {
                return ResourceManager.GetString("S_CrawlPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抓取规则 的本地化字符串。
        /// </summary>
        public static string S_CrawlRule {
            get {
                return ResourceManager.GetString("S_CrawlRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库文件路径 的本地化字符串。
        /// </summary>
        public static string S_DbFilePath {
            get {
                return ResourceManager.GetString("S_DbFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string S_Delete {
            get {
                return ResourceManager.GetString("S_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除 [{0}] ? 的本地化字符串。
        /// </summary>
        public static string S_DeleteConfirm {
            get {
                return ResourceManager.GetString("S_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string S_Describe {
            get {
                return ResourceManager.GetString("S_Describe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录值 的本地化字符串。
        /// </summary>
        public static string S_DnsRecordValue {
            get {
                return ResourceManager.GetString("S_DnsRecordValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 域名 的本地化字符串。
        /// </summary>
        public static string S_Domain {
            get {
                return ResourceManager.GetString("S_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从此ID开始下载 的本地化字符串。
        /// </summary>
        public static string S_DownloadFromCurId {
            get {
                return ResourceManager.GetString("S_DownloadFromCurId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载记录 的本地化字符串。
        /// </summary>
        public static string S_DownloadRecord {
            get {
                return ResourceManager.GetString("S_DownloadRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载结果 的本地化字符串。
        /// </summary>
        public static string S_DownloadResult {
            get {
                return ResourceManager.GetString("S_DownloadResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载时间 的本地化字符串。
        /// </summary>
        public static string S_DownloadTime {
            get {
                return ResourceManager.GetString("S_DownloadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑账号 的本地化字符串。
        /// </summary>
        public static string S_EditAccount {
            get {
                return ResourceManager.GetString("S_EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑抓取规则 的本地化字符串。
        /// </summary>
        public static string S_EditCrawlRule {
            get {
                return ResourceManager.GetString("S_EditCrawlRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑解析记录 的本地化字符串。
        /// </summary>
        public static string S_EditDnsRecord {
            get {
                return ResourceManager.GetString("S_EditDnsRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑乐谱 的本地化字符串。
        /// </summary>
        public static string S_EditPianoScore {
            get {
                return ResourceManager.GetString("S_EditPianoScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑同步配置 的本地化字符串。
        /// </summary>
        public static string S_EditSyncConfig {
            get {
                return ResourceManager.GetString("S_EditSyncConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string S_Enable {
            get {
                return ResourceManager.GetString("S_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出为分享包 的本地化字符串。
        /// </summary>
        public static string S_ExportForShare {
            get {
                return ResourceManager.GetString("S_ExportForShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线路 的本地化字符串。
        /// </summary>
        public static string S_Line {
            get {
                return ResourceManager.GetString("S_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动端路径 的本地化字符串。
        /// </summary>
        public static string S_MobilePath {
            get {
                return ResourceManager.GetString("S_MobilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string S_Modify {
            get {
                return ResourceManager.GetString("S_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 乐谱ID 的本地化字符串。
        /// </summary>
        public static string S_MusicId {
            get {
                return ResourceManager.GetString("S_MusicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string S_Name {
            get {
                return ResourceManager.GetString("S_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有已连接的可移动设备 的本地化字符串。
        /// </summary>
        public static string S_NoConnectedDevice {
            get {
                return ResourceManager.GetString("S_NoConnectedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件夹 的本地化字符串。
        /// </summary>
        public static string S_OpenFolder {
            get {
                return ResourceManager.GetString("S_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开播放器 的本地化字符串。
        /// </summary>
        public static string S_OpenPlayer {
            get {
                return ResourceManager.GetString("S_OpenPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string S_Password {
            get {
                return ResourceManager.GetString("S_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电脑端路径 的本地化字符串。
        /// </summary>
        public static string S_PcPath {
            get {
                return ResourceManager.GetString("S_PcPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理数量 的本地化字符串。
        /// </summary>
        public static string S_ProxyCount {
            get {
                return ResourceManager.GetString("S_ProxyCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码配置文件路径 的本地化字符串。
        /// </summary>
        public static string S_PwdConfigFilePath {
            get {
                return ResourceManager.GetString("S_PwdConfigFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string S_Refresh {
            get {
                return ResourceManager.GetString("S_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string S_Remark {
            get {
                return ResourceManager.GetString("S_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存更改 的本地化字符串。
        /// </summary>
        public static string S_SaveChanged {
            get {
                return ResourceManager.GetString("S_SaveChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string S_Setting {
            get {
                return ResourceManager.GetString("S_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 站点 的本地化字符串。
        /// </summary>
        public static string S_Site {
            get {
                return ResourceManager.GetString("S_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string S_Status {
            get {
                return ResourceManager.GetString("S_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 就绪 的本地化字符串。
        /// </summary>
        public static string S_StatusBarDefaultText {
            get {
                return ResourceManager.GetString("S_StatusBarDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子域名 的本地化字符串。
        /// </summary>
        public static string S_SubDomian {
            get {
                return ResourceManager.GetString("S_SubDomian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同步 的本地化字符串。
        /// </summary>
        public static string S_Sync {
            get {
                return ResourceManager.GetString("S_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同步路径配置 的本地化字符串。
        /// </summary>
        public static string S_SyncPathConfig {
            get {
                return ResourceManager.GetString("S_SyncPathConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tan8曲谱保存路径 的本地化字符串。
        /// </summary>
        public static string S_Tan8SheetSavePath {
            get {
                return ResourceManager.GetString("S_Tan8SheetSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TTL 的本地化字符串。
        /// </summary>
        public static string S_TTL {
            get {
                return ResourceManager.GetString("S_TTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string S_Type {
            get {
                return ResourceManager.GetString("S_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新时间 的本地化字符串。
        /// </summary>
        public static string S_UpdateTime {
            get {
                return ResourceManager.GetString("S_UpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用代理 的本地化字符串。
        /// </summary>
        public static string S_UseProxy {
            get {
                return ResourceManager.GetString("S_UseProxy", resourceCulture);
            }
        }
    }
}
